Moves common initialization to an init script and cleans up the module scripts

diff --git a/clean-up-pipelines-json/cleanup-json b/clean-up-pipelines-json/cleanup-json
--- a/clean-up-pipelines-json/cleanup-json
+++ b/clean-up-pipelines-json/cleanup-json
@@ -1,48 +1,51 @@
 #!/bin/bash
 
-PROPERTIES_FILE=$1
-RESOURCES_FILE=$2
-PRODUCT_NAME=$3
-OUTPUT_DIR=$4
+set -e
 
-if [ ! -d "$OUTPUT_DIR/modified" ]; then
-    mkdir -p $OUTPUT_DIR/modified
+source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/.init.sh
+
+###
+# Cleanups JSON from the `/api/v0/stage/:product_name/properties` endpoint into
+#   JSON for importing to the `task.sh` file.
+#
+# Parameters:
+#   {string} INPUT        The JSON file to cleanup
+#   {string} PRODUCT_NAME The name of the product whose JSON is being cleaned up
+##
+
+## Validation
+
+if [ ! -r "$INPUT" ]; then
+  ERR_CODE=4 error "Provided input file $INPUT does not exist or is not readable."
 fi
 
-if [[ -z "$PROPERTIES_FILE" ]]; then
-  echo "Provided file $PROPERTIES_FILE does not exist."
-  exit 1
-fi
+## Variables
 
-UPDATED_JSON=$(cat $PROPERTIES_FILE | jq -L $PWD 'import "library" as lib;
-   lib::walk(if type == "object" then del(.type) else . end)')
+declare -a DELETE=(type optional credential guid options configurable)
+declare JSON=$(cat "$INPUT")
 
-UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
-   lib::walk(if type == "object" then del(.optional) else . end)')
+## Main
 
-UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
-  lib::walk(if type == "object" then del(.credential) else . end)')
-
-UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
-  lib::walk(if type == "object" then del(.guid) else . end)')
-
-UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
-  lib::walk(if type == "object" then del(.options) else . end)')
-
-KEYS=$(echo "$UPDATED_JSON" | jq -r '.[] | keys[]')
-
-for i in $(echo $KEYS | sed "s/,/ /g")
-do
-    KEY=$(echo $i)
-    IS_NON_CONFIGURABLE=$(echo "$UPDATED_JSON" | jq --arg "key" "$KEY" '.properties[$key] | select(.configurable==false)')
-    if [[ ! -z "$IS_NON_CONFIGURABLE" ]]; then
-      UPDATED_JSON=$(echo "$UPDATED_JSON" | jq --arg "key" "$KEY" 'del(.properties[$key])')
-    fi
+log "Deleting non configurable properties"
+for KEY in $(echo "$JSON" | "$JQ_CMD" -r '.[] | keys[]' | sed "s/,/ /g"); do
+  IS_NON_CONFIGURABLE=$(echo "$JSON" | "$JQ_CMD" --arg "key" "$KEY" '.properties[$key] | select(.configurable==false)')
+  if [ ! -z "$IS_NON_CONFIGURABLE" ]; then
+    JSON=$(echo "$JSON" | "$JQ_CMD" --arg "key" "$KEY" 'del(.properties[$key])')
+  fi
+  unset IS_NON_CONFIGURABLE
 done
 
-UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
-  lib::walk(if type == "object" then del(.configurable) else . end)')
+log "Deleting keys: (${DELETE[@]}) from $INPUT"
+for key in "${DELETE[@]}"; do
+  JSON=$(echo "$JSON" | "$JQ_CMD" -L "$(__DIR__)" --arg 'key' "$key" 'import "library" as lib;
+    lib::walk(if type == "object" then del(.[$key]) else . end)')
+done
 
-echo "$UPDATED_JSON" | jq '.[]' > $OUTPUT_DIR/modified/$PRODUCT_NAME.json
+echo "$JSON" | "$JQ_CMD" '.[]' > "$OUTPUT"/"$PRODUCT_NAME"-modified.json
 
-./convert-json $OUTPUT_DIR/modified/$PRODUCT_NAME.json $RESOURCES_FILE $PRODUCT_NAME $OUTPUT_DIR
+
+echo "Wrote output to $OUTPUT/$PRODUCT_NAME-modified.json"
+
+## Cleanup
+
+unset __DIR__ DELETE JSON
diff --git a/clean-up-pipelines-json/convert-json b/clean-up-pipelines-json/convert-json
--- a/clean-up-pipelines-json/convert-json
+++ b/clean-up-pipelines-json/convert-json
@@ -1,42 +1,58 @@
 #!/bin/bash
 
-PROPERTIES_FILE=$1
-RESOURCES_FILE=$2
-PRODUCT_NAME=$3
-OUTPUT_DIR=$4
+set -e
 
-if [ ! -d "$OUTPUT_DIR/tasks/config-$PRODUCT_NAME" ]; then
-    mkdir -p "$OUTPUT_DIR/tasks/config-$PRODUCT_NAME"
+source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/.init.sh
+
+###
+# Converts a directory consisting of a properties file and a resource file into
+#   a `task.sh` script.
+#
+# Parameters:
+#   {string} INPUT        The JSON file to cleanup
+#   {string} PRODUCT_NAME The name of the product whose JSON is being cleaned up
+##
+
+## Validation
+
+if [ ! -d "$INPUT" ]; then
+  ERR_CODE=4 error "Provided input directory $INPUT does not exist."
 fi
 
-OUTFILE="$OUTPUT_DIR/tasks/config-$PRODUCT_NAME/task.sh"
-
+declare OUTFILE="$OUTPUT/$PRODUCT_NAME.sh"
 if [ -f "$OUTFILE" ]; then
-    rm -f "$OUTFILE"
+  log "Removing existing file: $OUTFILE"
+  rm -f "$OUTFILE"
 fi
-
 touch "$OUTFILE"
 
-echo -e "#!/bin/bash\n\n" >> "$OUTFILE"
+## Variables
+
+val='{"value": "$\(.key | split(".") | .[-1])"}'
+CONVERT_SCRIPT="
+to_entries |
+map(
+  if (.value.value | type) == \"object\"
+  then . + {\"value\": {\"secret\": $val}}
+  else . + {\"value\": $val} end
+) |
+from_entries"
+
+## Main
+
+log "Writing shabang line"
+echo -e "#!/bin/bash\n" >> "$OUTFILE"
 
 ## Properties
 
+log "Writing properties_config"
 echo 'properties_config=$(jq -n \' >> "$OUTFILE"
 
-val='{"value": "$\(.key | split(".") | .[-1])"}'
-IFS='' read -r -d '' CONVERT_SCRIPT << EOF
-to_entries |
-map(
-    if (.value.value | type) == "object"
-    then . + {"value": {"secret": $val}}
-    else . + {"value": $val} end
-) |
-from_entries
-EOF
+FILE="$INPUT/properties.json"
 
 ARGS=
-KEYS=$(cat "$PROPERTIES_FILE" | jq -r 'keys[] | split(".") | .[-1]')
-JSON=$(cat "$PROPERTIES_FILE" | jq "$CONVERT_SCRIPT" | sed 's/\"\(\$.*\)\"/\1/g')
+KEYS=$(cat "$FILE" | "$JQ_CMD" -r 'keys[] | split(".") | .[-1]')
+JSON=$(cat "$FILE" | "$JQ_CMD" "$CONVERT_SCRIPT" | sed 's/\"\(\$.*\)\"/\1/g')
 
 for key in $KEYS; do
   echo "  --arg $key \$$(echo $key | awk '{print toupper($0)}') \\" >> "$OUTFILE"
@@ -44,15 +60,18 @@ done
 
 echo "'$JSON'" >> "$OUTFILE"
 
-echo -e ')\n\n' >> "$OUTFILE"
+echo -e ')\n' >> "$OUTFILE"
 
 
 ## Resources
 
+FILE="$INPUT/resources.json"
+
+log "Writing resources_config"
 echo 'resources_config="{' >> "$OUTFILE"
 
-KEYS=$(cat "$RESOURCES_FILE" | jq -r '.resources | .[] | .identifier' )
-j=$(cat $RESOURCES_FILE | jq '.resources | length')
+KEYS=$(cat "$FILE" | "$JQ_CMD" -r '.resources | .[] | .identifier' )
+j=$(cat $FILE | "$JQ_CMD" '.resources | length')
 i=0
 for key in $KEYS; do
   echo -n "  \\\"$key\\\": {\\\"instances\\\": \$$(echo $key | sed 's/-/_/g' | awk '{print toupper($0)}')_INSTANCES}" >> "$OUTFILE"
@@ -65,14 +84,16 @@ for key in $KEYS; do
 done
 unset i j
 
-echo -e '}"\n\n' >> "$OUTFILE"
+echo -e '}"\n' >> "$OUTFILE"
 
 ## Network
 
+log "Writing network_config"
 echo 'network_config=$(jq -n \' >> "$OUTFILE"
 echo '  --arg network_name "$NETWORK_NAME" \ ' >> "$OUTFILE"
-echo '  --arg other_azs "$SERVICES_NW_AZS" \ ' >> "$OUTFILE"
-echo '  --arg singleton_az "$SERVICE_SINGLETON_JOB_AZ" \ ' >> "$OUTFILE"
+echo '  --arg other_azs "$OTHER_AZS" \ ' >> "$OUTFILE"
+echo '  --arg singleton_az "$SINGLETON_JOBS_AZ" \ ' >> "$OUTFILE"
+echo '  --arg services_network_name "$SERVICES_NETWORK_NAME" \ ' >> "$OUTFILE"
 echo "'" >> "$OUTFILE"
 echo '  {' >> "$OUTFILE"
 echo '    "network": {' >> "$OUTFILE"
@@ -81,13 +102,17 @@ echo '    },' >> "$OUTFILE"
 echo '    "other_availability_zones": ($other_azs | split(",") | map({name: .})),' >> "$OUTFILE"
 echo '    "singleton_availability_zone": {' >> "$OUTFILE"
 echo '      "name": $singleton_az' >> "$OUTFILE"
+echo '    },' >> "$OUTFILE"
+echo '    "service_network": {' >> "$OUTFILE"
+echo '      "name": $services_network_name' >> "$OUTFILE"
 echo '    }' >> "$OUTFILE"
 echo '  }' >> "$OUTFILE"
 echo "'" >> "$OUTFILE"
-echo -e ')\n\n' >> "$OUTFILE"
+echo -e ')\n' >> "$OUTFILE"
 
 ## Run
 
+log "Writing om-linux command"
 echo 'om-linux \' >> "$OUTFILE"
 echo '  --target https://$OPSMAN_DOMAIN_OR_IP_ADDRESS \' >> "$OUTFILE"
 echo '  --username "$OPS_MGR_USR" \' >> "$OUTFILE"
@@ -98,3 +123,9 @@ echo "  --product-name $PRODUCT_NAME \\" >> "$OUTFILE"
 echo '  --product-properties "$properties_config" \' >> "$OUTFILE"
 echo '  --product-network "$network_config" \' >> "$OUTFILE"
 echo '  --product-resources "$resources_config"' >> "$OUTFILE"
+
+log "Wrote output to $OUTFILE"
+
+## Cleanup
+
+unset OUTFILE FILE CONVERT_SCRIPT
